-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."quest_log_entry" add column "step" integer
--  not null default '10';
