version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: '/'
    schedule:
      interval: weekly
      day: friday
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: '/react'
    schedule:
      interval: weekly
    labels:
      - "dependencies"

