-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO
--     quest_tag (name, description)
-- VALUES
--     ('main', 'Main'), ('side', 'Side'), ('backstory', 'Backstory'), ('optional', 'Optional');
