services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    ports:
      - "8529:8529"
    secrets:
      - arango_root_password
    environment:
      ARANGO_ROOT_PASSWORD_FILE: /run/secrets/arango_root_password
    volumes:
      - arango-data:/var/lib/arangodb3
      - arango-apps:/var/lib/arangodb3-apps

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    secrets:
      - minio_root_password
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
    volumes:
      - minio-data:/data # Persisted storage
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    image: simply-the-quest-web:latest
    build:
      context: ../../
      dockerfile: apps/frontend/Dockerfile
    container_name: stq-web
    ports:
      - "3000:3000/tcp"

  web-api:
    image: simply-the-quest-web-api:latest
    build:
      context: ../../apps/backend/
    container_name: stq-web-api
    ports:
      - "8080:8080/tcp"
    secrets:
      - arango_root_password
    environment:
      ARANGODB_USER: root
      ARANGODB_HOST: http://arangodb:8529
      ARANGODB_PASS: /run/secrets/arango_root_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

secrets:
  arango_root_password:
    file: ./arangodb_root_password
  minio_root_password:
    file: ./minio_root_password

volumes:
  arango-data:
  arango-apps:
  minio-data:
