services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    ports:
      - "8529:8529"
    secrets:
      - arango_root_password
    environment:
      - ARANGO_ROOT_PASSWORD_FILE=/run/secrets/arango_root_password
    volumes:
      - arango-data:/var/lib/arangodb3
      - arango-apps:/var/lib/arangodb3-apps

secrets:
  arango_root_password:
    file: ./arangodb_root_password

volumes:
  arango-data:
  arango-apps:
